# Topics
- name: "Bug"
  color: "b60205"
  description: "Something isn't working as expected"
- name: "Feature request"
  color: "0e8a16"
  description: "An issue that will result in new functionality."
- name: "Help wanted"
  color: "4caf50"
  description: "Requires assistance to resolve or determine action steps."
- name: "Documentation"
  color: "c5def5"
  description: "Issues that affect the comprehension of the product."
- name: "Needs more info"
  color: "795548"
  description: "Requires assistance to resolve or determine action steps."

# Priority
- name: "🚨 Urgent"
  color: "d5232f"
  description: "Requires immediate intervention"