apiVersion: 1.0.0
secrets:
  aws_access_key_id:
    name: aws_access_key_id
    scope: [actions, dependabot]
    annotations:
      aws.example.com/src: aws-federated-sts
      aws.example.com/name: github-config-in-code
  aws_secret_access_key:
    name: AWS_SECRET_ACCESS_KEY
    scope: [actions, dependabot]
    annotations:
      aws.example.com/src: aws-federated-sts
      aws.example.com/name: github-config-in-code
  aws_session_token:
    name: AWS_SESSION_TOKEN
    scope: [actions, dependabot]
    annotations:
      aws.example.com/src: aws-federated-sts
      aws.example.com/name: github-config-in-code
  aws_default_region:
    name: AWS_DEFAULT_REGION
    scope: [actions, dependabot]
    annotations:
      aws.example.com/src: aws-federated-sts
      aws.example.com/name: github-config-in-code
      aws.example.com/path: public-key
  signing_key:
    name: ARTIFACTS_SIGN_KEY
    scope: [actions]
    annotations:
      aws.example.com/src: aws-secretsmanager
      aws.example.com/name: github-config-in-code
      aws.example.com/path: public-key
  signing_key_pub:
    name: ARTIFACTS_SIGN_KEY_PUB
    scope: [actions]
    annotations:
      aws.example.com/src: aws-secretsmanager
      aws.example.com/name: github-config-in-code
      aws.example.com/path: public-key

