repository:
  name: github-config-in-code
  description: Fiddling with the github folder conventions
  homepage: https://github.com/jrbeverly/github-config-in-code
  topics: github, probot
  private: false

  # Components
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false

  # Git Options
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true

  # Security Scanning
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Branch protection policy
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
      enforce_admins: true
      required_linear_history: true