name: GitHub - Labels
permissions: read-all

on:
  push:
    branches: 
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/labels.yml

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions: 
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@b0e28b5ac45a892f91e7d036f8200cf5ed489415 # v3 # v2.4.0
      - uses: crazy-max/ghaction-github-labeler@52525cb66833763f651fc34e244e4f73b6e07ff5 # v3
        with:
          yaml-file: .github/labels.yml
