name: Misspells
permissions: read-all

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
      - uses: reviewdog/action-misspell@83fd95f00e0c172832739f5b4af713aa809f1436 # v1
        with:
          locale: "US"
          level: error
